auth.py
"""Routes for user authentication."""
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import current_user, login_user
from forms import LoginForm, SignupForm
from models import db, User
from app import login_manager


# Blueprint Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    User sign-up page.
    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(username=form.username.data).first()
        if existing_user is None:
            user = User(
                username=form.username.data,
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user, remember=True)  # Log in as newly created user
            return redirect(url_for('main_bp.dashboard'))
        flash('A user already exists with that email address.')
    return render_template(
        'signup.jinja2',
        title='Create an Account.',
        form=form,
        template='signup-page',
        body="Sign up for a user account."
    )


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.
    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('main_bp.dashboard'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template(
        'login.jinja2',
        form=form,
        title='Log in.',
        template='login-page',
        body="Log in with your User account."
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

routes.py
"""Logged-in page routes."""
from flask import Blueprint, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required, logout_user

from app import db
from forms import EditForm, PlayForm

# Blueprint Configuration
from models import Band, BAND_STATES, PlayedBand, PlayedTags

from numpy.random import choice

main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


def index(bandsform=None, newbandsform=None):
    bands = Band.query.filter_by(user_id=current_user.id).all()

    if not bandsform:
        bandsform = EditForm(BAND_STATES['approved'])
        bandsform.fill_area([b for b in bands if b.state == BAND_STATES['approved']])

    if not newbandsform:
        newbandsform = EditForm(BAND_STATES['queued'])
        newbandsform.fill_area([b for b in bands if b.state == BAND_STATES['queued']])

    playform = PlayForm()

    played_bands = PlayedBand.query.filter_by(user_id=current_user.id).order_by(PlayedBand.date.desc()).limit(10).all()
    played_tags = {t.tags for t in
                   PlayedTags.query.filter_by(user_id=current_user.id).order_by(PlayedTags.date.desc()).limit(10).all()}

    return render_template(
        'dashboard.jinja2',
        title='Oblibands',
        template='dashboard-template',
        current_user=current_user,
        playform=playform,
        bandsform=bandsform,
        newbandsform=newbandsform,
        played_bands=played_bands,
        played_tags=played_tags
    )


@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
    return index()


@main_bp.route('/edit', methods=['POST'])
@login_required
def edit():
    bandsform = EditForm(BAND_STATES['approved'])
    if bandsform.validate_on_submit():
        try:
            edited_bands = bandsform.parse_bands(current_user)
            edited_bands = [db.session.merge(band) for band in edited_bands]
            to_delete_bands = [b for b in current_user.bands
                               if b.state == BAND_STATES['approved'] and b not in edited_bands]
            for b in to_delete_bands:
                db.session.delete(b)
            db.session.commit()
            bandsform.fill_area(edited_bands)
        except:
            flash('Cannot save, respect the input format!')
    else:
        raise Exception('Should not happend')

    return index(bandsform=bandsform)


@main_bp.route('/queue', methods=['POST'])
@login_required
def queue():
    newbandsform = EditForm(BAND_STATES['queued'])
    if newbandsform.validate_on_submit():
        try:
            edited_bands = newbandsform.parse_bands(current_user)
            edited_bands = [db.session.merge(band) for band in edited_bands]
            to_delete_bands = [b for b in current_user.bands
                               if b.state == BAND_STATES['queued'] and b not in edited_bands]
            for b in to_delete_bands:
                db.session.delete(b)
            db.session.commit()
            newbandsform.fill_area(edited_bands)
        except:
            flash('Cannot save, respect the input format!')
    else:
        raise Exception('Should not happend')

    return index(newbandsform=newbandsform)


class SpotifyEngine:
    BASE_LINK = "https://open.spotify.com/search/"

    @classmethod
    def completeUrl(cls, band):
        return cls.BASE_LINK + band.name


class YoutubeEngine:
    BASE_LINK = "https://www.youtube.com/results?search_query="

    @classmethod
    def completeUrl(cls, band):
        escaped_name = band.name.replace(" ", "+")
        return cls.BASE_LINK + escaped_name


class DefaultEngine(YoutubeEngine):
    @classmethod
    def completeUrl(cls, band):
        if band.url:
            return band.url
        return super().completeUrl(band)


SUPPORTED_ENGINES = {
    'default': DefaultEngine,
    'spotify': SpotifyEngine,
    'youtube': YoutubeEngine
}


@main_bp.route('/play', methods=['GET', 'POST'])
@login_required
def play():
    if request.method == 'POST':
        playform = PlayForm()
        if playform.validate_on_submit():
            engine_name = playform.engineselect.data
            tags_string = playform.tagsbox.data
            if playform.playsubmit.raw_data[0] != 'Let\'s rock!':
                tags_string = playform.playsubmit.raw_data[0]
            new_bands = playform.queueselect.data
    else:
        engine_name = request.args.get('engine', default='default', type=str)
        tags_string = request.args.get('tags', default='', type=str)
        new_bands = request.args.get('newbands', default=False, type=bool)
    engine = SUPPORTED_ENGINES.get(engine_name, DefaultEngine)
    tags = [t.strip() for t in tags_string.split('/') if t.strip() != '']

    if new_bands:
        bands = Band.query.filter_by(user_id=current_user.id, state=BAND_STATES['queued']).all()
    else:
        bands = Band.query.filter_by(user_id=current_user.id, state=BAND_STATES['approved']).all()

    if tags:
        bands = [b for b in bands if any(t in b.tags for t in tags)]

    if not bands:
        flash('Nothing to play!')
        return redirect(url_for('main_bp.dashboard'))

    ratings = [b.rating for b in bands]
    total = sum(ratings)
    probabilities = [r / total for r in ratings]
    band = choice(bands, 1, p=probabilities)[0]
    url = engine.completeUrl(band)

    played_band = PlayedBand(band_name=band.name, url=url, user_id=current_user.id)
    played_tags = PlayedTags(tags=tags_string, user_id=current_user.id)
    db.session.add(played_band)
    db.session.add(played_tags)
    db.session.commit()

    return redirect(url)


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

templates/dashboard.jinja2
{% extends "layout.jinja2" %}

{% block content %}

    {% if current_user.is_authenticated %}
        <p>Let's rock, {{ current_user.username }}!</p>
        <a href="{{ url_for('main_bp.logout') }}">Log out</a>

        <p class="form-wrapper">

            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}

            <h2>Play</h2>
            <form action="{{ url_for('main_bp.play') }}" method="POST">
                {{ playform.csrf_token }}

                <fieldset class="engine">
                    {{ playform.engineselect.label }}
                    {{ playform.engineselect }}
                </fieldset>
                <fieldset class="queueselect">
                    {{ playform.queueselect.label }}
                    {{ playform.queueselect }}
                </fieldset>
                <fieldset class="tags">
                    {{ playform.tagsbox.label }}
                    {% for tags in played_tags %}
                        <input type="submit" name="playsubmit" value="{{ tags }}">
                    {% endfor %}
                    {{ playform.tagsbox }}
                </fieldset>

                <div class="submit-button">
                    {{ playform.playsubmit }}
                </div>
            </form>

            <h2>Latest</h2>
            {% for record in played_bands %}
                <a href="{{ record.url }}">{{ record.band_name }}</a>
            {% endfor %}

            <h2>Your bands</h2>
            <p>Example format:
<pre>&lt;name&gt;\t&lt;rating&gt;\t&lt;tag1/tag2&gt;\t&lt;url&gt;

Metallica           	1.0	heavy/thrash
The Rolling Stones  	0.5	rock	https://www.youtube.com/channel/UCB_Z6rBg3WW3NL4-QimhC2A</pre>
            </p>

            <form action="{{ url_for('main_bp.edit') }}" method="POST">
                {{ bandsform.csrf_token }}

                <fieldset class="bands">
                    {{ bandsform.editarea.label }}
                    {{ bandsform.editarea }}
                    {% if bandsform.editarea.errors %}
                        <ul class="errors">
                            {% for error in bandsform.editarea.errors %}
                                <li>{{ error }}</li>{% endfor %}
                        </ul>
                    {% endif %}
                </fieldset>

                <div class="submit-button">
                    {{ bandsform.editsubmit }}
                </div>
            </form>

            <h2>New bands</h2>

            <form action="{{ url_for('main_bp.queue') }}" method="POST">
                {{ newbandsform.csrf_token }}

                <fieldset class="queue">
                    {{ newbandsform.editarea.label }}
                    {{ newbandsform.editarea }}
                    {% if newbandsform.editarea.errors %}
                        <ul class="errors">
                            {% for error in newbandsform.editarea.errors %}
                                <li>{{ error }}</li>{% endfor %}
                        </ul>
                    {% endif %}
                </fieldset>

                <div class="submit-button">
                    {{ newbandsform.editsubmit }}
                </div>
            </form>

        </div>

    {% endif %}

{% endblock %}

templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{{ title }}</title>
</head>

<body class="{{ template }}">
<div class="container">
  {% block content %}{% endblock %}
</div>
</body>

</html>

templates/login.jinja2
{% extends "layout.jinja2" %}

{% block content %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Log In</h1>

    <form method="POST">
      {{ form.csrf_token }}

      <fieldset class="username">
        {{ form.username.label }}
        {{ form.username(placeholder='kolousek42') }}
        {% if form.username.errors %}
          <ul class="errors">
            {% for error in form.username.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.username.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

      <div class="login-signup">
        <span>Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a></span>
      </div>

    </form>
  </div>
{% endblock %}

templates/signup.jinja2
{% extends "layout.jinja2" %}

{% block content %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Sign Up</h1>

    <form method="POST">
      {{ form.csrf_token }}

      <fieldset class="username">
        {{ form.username.label }}
        {{ form.username(placeholder='kolousek42') }}
        {% if form.username.errors %}
          <ul class="errors">
            {% for error in form.username.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="confirm">
        {{ form.confirm.label }}
        {{ form.confirm }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>

    <div class="login-signup">
      <span>Already have an account? <a href="{{ url_for('auth_bp.login') }}">Log in.</a></span>
    </div>
  </div>
{% endblock %}